<a href="https://colab.research.google.com/github/Muhammadkalleem/Background-Changer/blob/main/numpy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([10,20,30])
b = np.array([100,200,300])
print(a+b) ## to check the type
print(type(a))

[110 220 330]
<class 'numpy.ndarray'>


In [9]:
c= np.array([[12,12,12], [32,45,88] , [45,32,88]])
d= np.array([[3,2,1] , [4,3,2],[5,4,8]])
print(c*d)

[[ 36  24  12]
 [128 135 176]
 [225 128 704]]


In [12]:
arr1 = np.array([23,11,23,12,89,212])
print(arr[0:2])

arr2 = np.array([[121,43,23,12,99],[10,20,30,30,40]])
print(arr2[0:3,0:4])

[23 11]
[[121  43  23  12]
 [ 10  20  30  30]]


In [15]:
a = np.array([[1,2,3,4,5,6], [12,12,32,54,3,1]])
print(np.size(a))

print(a.astype(str))
print(a.astype(float))


12
[['1' '2' '3' '4' '5' '6']
 ['12' '12' '32' '54' '3' '1']]
[[ 1.  2.  3.  4.  5.  6.]
 [12. 12. 32. 54.  3.  1.]]


In [18]:
basim = np.array([[2,3,4,5,6]])
malahim = np.array([2,2,2,2,2])

print(np.power(basim,malahim))

[[ 4  9 16 25 36]]


In [32]:
a = np.array([25,9,144,512])

print(np.sqrt(a))


var1= np.array([2,3,4,5,3])
var2 = np.array([6,7,8,1,2])

print(np.concatenate((([var1,var2]))))

[ 5.        3.       12.       22.627417]
[2 3 4 5 3 6 7 8 1 2]
